apiVersion: v1
data:
  my_server_block.conf: |
    server {
      listen 8080;
      location / {
        root /app;
        index index.html;
        autoindex on;
      }

      location = /robots.txt {
        root /var/www/html;   # folder where robots.txt lives
      }

      #rewrite ^/(.*[^/])$ $scheme://$http_host/$1/ permanent;
      port_in_redirect off;
    }
kind: ConfigMap
metadata:
  name: nginx-config
